project:
  type: website
  output-dir: docs

website:
  title: "Francesca Capuano â€” R Tutorials"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Acceptability Ratings
        href: tutorials/acceptability-ratings.qmd
      - text: Power Analysis
        href: tutorials/power-analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

